### PR TITLE
fix: [CO-1453] SearchAllDomainsByFeature sometime fails to complete accounts while adding to a group chat on wsc

### PR DESCRIPTION
**Pull request by mbarto**
* introduced global config carbonioSearchAllDomainsByFeature (FALSE/TRUE, defaults to FALSE) to extends search to all domains (defaults to the user domain only)

```
zmprov mcf carbonioSearchAllDomainsByFeature TRUE
```

 * fixed search to include users on default COS, when default COS has WSC enabled

### CODE REVIEW

**Comment by sonersivri** [comment]
@mbarto changes should be added to CHANGELOG.md
`release-it --ci` can be used.

**Review by matteobaglini — APPROVED** [review]

**Comment by keshavbhatt** [comment]
@mbarto can you also please update the title of the PR to reflect it is related to `SearchAllDomainsByFeature` rather than `AutoComplete` which is a totally different API.

**Comment by keshavbhatt** [comment]
@mbarto have you also explored possibility of taking a request attribute/paramter to differ the API response? I would add an attribute for this only if it is really required.

**Review by keshavbhatt — APPROVED** [review]

**Review by drazen04 — APPROVED** [review]

**Comment by mbarto** [comment]
> @mbarto have you also explored possibility of taking a request attribute/paramter to differ the API response? I would add an attribute for this only if it is really required.

@keshavbhatt we evaluated this option, but it is a security concern to let user search on all domains if not intended, so we decided this is something the admin needs to configure globally through a specific config

**Comment by mbarto** [comment]
> @mbarto can you also please update the title of the PR to reflect it is related to `SearchAllDomainsByFeature` rather than `AutoComplete` which is a totally different API.

changed, thx

**Comment by mbarto** [comment]
> @mbarto changes should be added to CHANGELOG.md `release-it --ci` can be used.

done

**Pull request merged**
