### PR TITLE
CO-1133 define amavis white/black list attribute scope

### PR DESCRIPTION
**Pull request by mbarto**
:bell: needed by https://github.com/zextras/carbonio-mails-ui/pull/591

### CODE REVIEW

**Review by matteobaglini — APPROVED** [review]

**Review by drazen04 — APPROVED** [review]

**Comment by keshavbhatt** [comment]
Hi @mbarto, we also need to run `mvn antrun:run@generate-zattr-rights` since we modified `attrs.xml` file.

**Comment by mbarto** [comment]
> Hi @mbarto, we also need to run `mvn antrun:run@generate-zattr-rights` since we modified `attrs.xml` file.

Hi @keshavbhatt we didn't directly modified attrs.xml, but one dedicated to amavis attributes (amavisd-new-attrs.xml). Is this needed also in this case?
thx

**Comment by keshavbhatt** [comment]
> > Hi @mbarto, we also need to run `mvn antrun:run@generate-zattr-rights` since we modified `attrs.xml` file.
> 
> Hi @keshavbhatt we didn't directly modified attrs.xml, but one dedicated to amavis attributes (amavisd-new-attrs.xml). Is this needed also in this case? thx

Yes, it seems we need it also here. I just ran the command and it updated `ZAttrAccount.java`

**Review by keshavbhatt — APPROVED** [review]

**Comment by matteobaglini** [comment]
@keshavbhatt @mbarto `ZAttrAccount.java` updated. :-)

**Review by sonersivri — APPROVED** [review]

**Pull request merged**
