### PR TITLE
!fix(CO-1244): QAFix stop return 500 for any error and replace it with 422

### PR DESCRIPTION
**Pull request by matteobaglini**
Carbonio return `500` HTTP Status Code for any server error, even for application specific error like account not found.

Following the SOAP spec we can use any `4XX` or `5XX` for failures, so we choose `422 Unprocessable Content` as replace for `500`.

NOTE: this is a small but radical change in the public protocol so it can lead to BREAKING CHANGES so we are checking possible affected repositories.

### CODE REVIEW

**Review by mbarto — APPROVED** [review]

**Review by nomanAli95 — APPROVED** [review]

**Review by drazen04 — APPROVED** [review]

**Review by keshavbhatt — APPROVED** [review]
We probably need to align UI to adapt this change.

**Review by sonersivri — APPROVED** [review]

**Comment by aheeva-yuliya** [comment]
if it's a fix merge to main than

**Comment by nomanAli95** [comment]
Guys, any news on this? This is very important for WSC and Files, if there's anything I can do to merge this, please let me know

**Comment by matteobaglini** [comment]
> Guys, any news on this? This is very important for WSC and Files, if there's anything I can do to merge this, please let me know

@nomanAli95 We have done all required checks. Now we just have to wait the CI and then merge it.

**Pull request merged**
