### PR TITLE
feat(CO-625): briefcase removal

### PR DESCRIPTION
**Pull request by Polpetta**

### CODE REVIEW

**Comment by frisonisland** [comment]
@Polpetta probably I removed all qa unittest files in https://github.com/Zextras/carbonio-mailbox/pull/217.
After you pushed everything try to recompile and push without linting the ZAttr* files

**Comment by Polpetta** [comment]
> @Polpetta probably I removed all qa unittest files in #217. After you pushed everything try to recompile and push without linting the ZAttr* files

I'm not linting ZAttr files, is `pre-commit` that checks them. I don't know why we have different results for the same setup :shrug:

**Comment by frisonisland** [comment]
> > @Polpetta probably I removed all qa unittest files in #217. After you pushed everything try to recompile and push without linting the ZAttr* files
> 
> I'm not linting ZAttr files, is `pre-commit` that checks them. I don't know why we have different results for the same setup shrug

I know, it's just annoying because if you compile it generates them then you push and it complains about linting every time. Maybe we can add them to the ignore list along with attrs.xml

**Review by frisonisland — APPROVED** [review]

**Review by keshavbhatt — APPROVED** [review]
LGTM.

**Review by keshavbhatt — CHANGES_REQUESTED** [review]
Fix the failing test by removing Briefcase [from](https://github.com/Zextras/carbonio-mailbox/blob/feature/CO-625-briefcase-removal/store/src/test/java/com/zimbra/cs/service/mail/GetFolderTest.java#L112)

**Comment by Polpetta** [comment]
Yeah I missed it when removing all the briefcase searches

**Comment by keshavbhatt** [comment]
There are still some references of removed attributes in this file [GetInfoResponse.json](https://github.com/Zextras/carbonio-mailbox/blob/feature/CO-625-briefcase-removal/soap/src/test/java/com/zimbra/soap/account/GetInfoResponse.json)
Please remove them to avoid confusion in future.

**Comment by Polpetta** [comment]
It's a very old file and I can see there are already old, removed or discontinued attributes in there. No point to remove them and wait for another Jenkins approval. Merging as it is

**Pull request merged**
